# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61d07d7623ed0aa486b111785b9a7226124ba3dca7f39347fb4ebf9042106eaddafdd95699a6c806c3deca589541258b68383c01c1eed888adb284e81338040

test:
  secret_key_base: 94f71689398687338e8b23f7fca96c742d341bf3c0245565618f373b1c5465b177c7265f6302b1dc7b6139d65d42812884202e1c2a059b8c3cc6cde6e76c9996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
