# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d84ac9113c8a158b0a6c0f218be686e2a30a0b6bb2a8f5a520d0d501d3ca1b754dd4c14e24c89dd0086a4c26993e2da19f450c69288033d078a581e96d100902

test:
  secret_key_base: e3502df17b743bad3d1f05745242fb38a63eaa750b280e1766c0f28ded94f6425642bbe8cb6bb1780898bc3c4595b6493a5ba10aacf31597b42473f5692c4d77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
