# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5522eca7a7ac7993b499debe44a3a20471656685de7ac31c3d2dafbb00ac2287013af22e3dc49841f8788edc256f16c967355d7ec734563122d2e335f9f1314

test:
  secret_key_base: 04e28e7fe5c0ccc0b4f969a9acfc913fe44c9dd5e81caa80d2754286bc34c8495faf0e71c471594d724fbdd665ccb4d30c10a395aab4593237fb14b22f564a79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
